### ISSUE TITLE
Bug Literaturseite Sprachwahl

### ISSUE THREAD

**Issue by cnoss** [lucascranach/cranach-artefacts#27]
In der gleichen Ansicht gibt es oben rechts drei kleine gelbe Punkte. Wenn ich darauf klicke passiert nichts. Da sollte bitte die Spracheinstellung sein.

Bug kam von Gunnar via Mail

**Comment by yannic-bruegger** [comment]
Fix sollte jetzt im internen Bereich inklusive neuem Export  bereitgestellt sein. @CranacharchivGunnar könntest du noch einmal testen?

**Comment by CranacharchivGunnar** [comment]
Super, im internen Bereich funktioniert es jetzt!

**Comment by yannic-bruegger** [comment]
Ok, top. Habe das gleiche Update jetzt für die Live-Umgebung veröffentlicht. Könntet ihr das einmal prüfen? Vielen Dank und nachher einen schönen Feierabend!

**Comment by CranacharchivGunnar** [comment]
Perfect! Closed! Danke Euch und ebenso einen schönen Abend!
