### ISSUE TITLE
Fehlerhafte Anzeige der Quellenangabe einer Datierung

### ISSUE THREAD

**Issue by cdaJana** [lucascranach/cranach-artefacts#37]
### URL of the buggy page?

https://lucascranach.org/de/PRIVATE_NONE-P283

### Contact Details

JH

### What happened?

Die Angabe ist in TMS korrekt. Am Frontend sieht es aus, als wäre daraus eine Aufzählung geworden.

![Image](https://github.com/lucascranach/cda-orga/assets/153098069/5ff7b1aa-2831-4810-9a36-6bc8f1e205ae)

**Comment by yannic-bruegger** [comment]
![Image](https://github.com/lucascranach/cranach-artefacts/assets/36576062/b93d35d1-0e21-4512-8e19-d7f4595f6fdf)

**Comment by cdaJana** [comment]
Super!
Kannst du es gleich ans Frontend packen?

**Comment by cdaJana** [comment]
Die Datierung wird am Frontend jetzt richtig angezeigt... aber die Abbildung ist weg

**Comment by yannic-bruegger** [comment]
Ich bin dran, sorry für die Umstände!

**Comment by yannic-bruegger** [comment]
Sollte jetzt wieder funktionieren. Da ist vor ein paar tagen schon etwas schief gelaufen, was durch die Veröffentlichung jetzt erst bemerkt wurde.

**Comment by cdaJana** [comment]
Funktioniert! Vielen Dank fürs schnelle fixen
